# Generated by Django 3.2.6 on 2021-10-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='titre',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
