# Generated by Django 3.2.6 on 2021-10-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_blog_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='blogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idB', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idB', to='accueil.blog')),
                ('idT', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idT', to='accueil.tags')),
            ],
        ),
    ]
