# Generated by Django 3.2.6 on 2021-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_blogtags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
