# Generated by Django 3.2.6 on 2021-10-20 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 10, 20, 1, 21, 4, 721475), max_length=10, null=True),
        ),
    ]
