# Generated by Django 3.2.6 on 2021-10-20 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default=datetime.date(2021, 10, 20), max_length=10, null=True),
        ),
    ]
