# Generated by Django 3.2.6 on 2021-12-11 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0006_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default=datetime.date(2021, 12, 11), max_length=10, null=True),
        ),
    ]
