# Generated by Django 3.2.6 on 2021-08-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('qte', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('idCat', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idCat', to='commerce.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(null=True)),
                ('idP', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idP', to='commerce.produit')),
                ('idU', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idU', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, null=True)),
                ('montant', models.FloatField(null=True)),
                ('idC', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idC', to=settings.AUTH_USER_MODEL)),
                ('idP', models.ManyToManyField(to='commerce.Produit')),
            ],
        ),
    ]
