# Generated by Django 3.2.6 on 2021-08-07 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0002_produit_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='idP',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='idU',
        ),
        migrations.CreateModel(
            name='assoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idP', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idP', to='commerce.produit')),
                ('idPa', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idPa', to='commerce.panier')),
                ('idU', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idU', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
