# Generated by Django 3.2.6 on 2021-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20210807_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='qte',
        ),
        migrations.AddField(
            model_name='produit',
            name='qteS',
            field=models.IntegerField(null=True),
        ),
    ]
