# Generated by Django 3.2.6 on 2021-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20210818_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='qteS',
        ),
        migrations.AddField(
            model_name='panier',
            name='qte',
            field=models.IntegerField(null=True),
        ),
    ]
