# Generated by Django 3.2.6 on 2021-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='first',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='last',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='postal',
            field=models.IntegerField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
