# Generated by Django 3.2.6 on 2021-08-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_commande_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='idP',
        ),
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCommande', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idCommande', to='commerce.commande')),
                ('idProduit', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idProduit', to='commerce.produit')),
            ],
        ),
    ]
