# Generated by Django 3.2.6 on 2021-08-25 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0009_auto_20210825_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande_Produit_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='idC',
        ),
        migrations.DeleteModel(
            name='Commande_Produit',
        ),
        migrations.AddField(
            model_name='commande_produit_user',
            name='idCommande',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idCommande', to='commerce.commande'),
        ),
        migrations.AddField(
            model_name='commande_produit_user',
            name='idProduit',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idProduit', to='commerce.produit'),
        ),
        migrations.AddField(
            model_name='commande_produit_user',
            name='idUser',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
