# Generated by Django 3.2.6 on 2021-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20210825_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_produit_user',
            name='qte',
            field=models.IntegerField(null=True),
        ),
    ]
