# Generated by Django 3.2.6 on 2021-08-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_commande_produit_user_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='trans',
            field=models.IntegerField(null=True),
        ),
    ]
