# Generated by Django 3.2.6 on 2021-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_alter_commande_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statusT',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
