# Generated by Django 3.2.6 on 2021-08-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0015_auto_20210827_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='idPr',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idPr', to='commerce.produit'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='wish',
            name='idUs',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idUs', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.DeleteModel(
            name='WUP',
        ),
    ]
